apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickmorty
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rickmorty
  template:
    metadata:
      labels:
        app: rickmorty
    spec:
      containers:
        - name: rickmorty
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ghcr-creds
